some new changes

diff --git a/zshrc/zshrc_venv_grml b/zshrc/zshrc_venv_grml
--- a/zshrc/zshrc_venv_grml
+++ b/zshrc/zshrc_venv_grml
@@ -274,7 +274,7 @@ function zrcautoload () {
     return 0
 }
 
-# The following is the â€˜add-zsh-hookâ€™ function from zsh upstream. It is
+# The following is the ‘add-zsh-hook’ function from zsh upstream. It is
 # included here to make the setup work with older versions of zsh (prior to
 # 4.3.7) in which this function had a bug that triggers annoying errors during
 # shell startup. This is exactly upstreams code from f0068edb4888a4d8fe94def,
@@ -1504,7 +1504,7 @@ bind2maps emacs viins       -- -s '^x1' jump_after_first_word
 bind2maps emacs viins       -- -s "^x^x" hist-complete
 
 # insert unicode character
-# usage example: 'ctrl-x i' 00A7 'ctrl-x i' will give you an Â§
+# usage example: 'ctrl-x i' 00A7 'ctrl-x i' will give you an §
 # See for example http://unicode.org/charts/ for unicode characters code
 #k# Insert Unicode character
 bind2maps emacs viins       -- -s '^xi' insert-unicode-char
@@ -2076,7 +2076,7 @@ function grml_prompt_setup () {
     emulate -L zsh
     autoload -Uz vcs_info
     # The following autoload is disabled for now, since this setup includes a
-    # static version of the â€˜add-zsh-hookâ€™ function above. It needs to be
+    # static version of the ‘add-zsh-hook’ function above. It needs to be
     # re-enabled as soon as that static definition is removed again.
     #autoload -Uz add-zsh-hook
     add-zsh-hook precmd prompt_$1_precmd
@@ -2531,7 +2531,7 @@ function grml_control_xterm_title () {
 }
 
 # The following autoload is disabled for now, since this setup includes a
-# static version of the â€˜add-zsh-hookâ€™ function above. It needs to be
+# static version of the ‘add-zsh-hook’ function above. It needs to be
 # re-enabled as soon as that static definition is removed again.
 #zrcautoload add-zsh-hook || add-zsh-hook () { :; }
 if [[ $NOPRECMD -eq 0 ]]; then
@@ -3733,7 +3733,10 @@ if check_com -c hg ; then
 
 fi # end of check whether we have the 'hg'-executable
 
-# grml-small cleanups
+# disable bracketed paste mode for dumb terminals
+[[ "$TERM" == dumb ]] && unset zle_bracketed_paste
+
+# grml-small cleanups and workarounds
 
 # The following is used to remove zsh-config-items that do not work
 # in grml-small by default.
@@ -3742,6 +3745,8 @@ fi # end of check whether we have the 'hg'-executable
 # sources if it is there).
 
 if (( GRMLSMALL_SPECIFIC > 0 )) && isgrmlsmall ; then
+
+    # Clean up
 
     unset "abk[V]"
     unalias    'V'      &> /dev/null
@@ -3753,6 +3758,36 @@ if (( GRMLSMALL_SPECIFIC > 0 )) && isgrmlsmall ; then
     unfunction manzsh   &> /dev/null
     unfunction man2     &> /dev/null
 
+    # Workarounds
+
+    # See https://github.com/grml/grml/issues/56
+    if ! [[ -x ${commands[dig]} ]]; then
+        function dig_after_all () {
+            unfunction dig
+            unfunction _dig
+            autoload -Uz _dig
+            unfunction dig_after_all
+        }
+        function dig () {
+            if [[ -x ${commands[dig]} ]]; then
+                dig_after_all
+                command dig "$@"
+                return "$!"
+            fi
+            printf 'This installation does not include `dig'\'' for size reasons.\n'
+            printf 'Try `drill'\'' as a light weight alternative.\n'
+            return 0
+        }
+        function _dig () {
+            if [[ -x ${commands[dig]} ]]; then
+                dig_after_all
+                zle -M 'Found `dig'\'' installed. '
+            else
+                zle -M 'Try `drill'\'' instead of `dig'\''.'
+            fi
+        }
+        compdef _dig dig
+    fi
 fi
 
 zrclocal
@@ -3770,22 +3805,21 @@ zrclocal
 # Local variables:
 # mode: sh
 # End:
-
-
-source /usr/share/zsh/plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
-export WORKON_HOME=~/.virtualenvs      
-source /usr/bin/virtualenvwrapper.sh
-function virtual_env_prompt () {
-        REPLY=${VIRTUAL_ENV+(${VIRTUAL_ENV:t}) }
-    }
-    grml_theme_add_token virtual-env -f virtual_env_prompt '%F{magenta}' '%f'
+source /usr/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
+function virtual_env_prompt () { 
+    :   REPLY=${VIRTUAL_ENV+(${VIRTUAL_ENV:t}) }
+    }    
+    grml_theme_add_token virtual-env -f virtual_env_prompt '%F{magenta}' '%f' 
 
 autoload -U colors && colors
     zstyle ':vcs_info:*' enable git
-    zstyle ':vcs_info:*' check-for-changes true
+    zstyle ':vcs_info:*' check-for-changes true 
     zstyle ':vcs_info:*' unstagedstr '!'
     zstyle ':vcs_info:*' stagedstr '+'
     zstyle ':vcs_info:git*' formats "%{${fg[cyan]}%}[%{${fg[blue]}%}%b%{${fg[yellow]}%}%m%u%c%{${fg[cyan]}%}]%{$reset_color%}"
 
 
-zstyle ':prompt:grml:left:setup' items rc change-root virtual-env path vcs percent
+zstyle ':prompt:grml:left:setup' items rc change-root virtual-env user at host path vcs percent 
+
+alias prxy='export http_proxy=172.16.20.2:3128 && export https_proxy=172.16.20.2:3128'
+alias nprxy='export http_proxy= && export https_proxy='
